// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDWdchsUpDJFtg96PH6shv4W75z2ZmIUA',
    appId: '1:673637170831:web:06cfa34a4f3dbc4a80fafa',
    messagingSenderId: '673637170831',
    projectId: 'koperasiundiksha-shandi',
    authDomain: 'koperasiundiksha-shandi.firebaseapp.com',
    storageBucket: 'koperasiundiksha-shandi.firebasestorage.app',
    measurementId: 'G-F8S4MRHXY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeCkhHh1TICHAUGrGNrw0IJz12N-kENkk',
    appId: '1:673637170831:android:6a9086552db2441080fafa',
    messagingSenderId: '673637170831',
    projectId: 'koperasiundiksha-shandi',
    storageBucket: 'koperasiundiksha-shandi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKh14iH24uTYEDBvKBf47Ap-gouJzm1M8',
    appId: '1:673637170831:ios:93c79c6f6368db8e80fafa',
    messagingSenderId: '673637170831',
    projectId: 'koperasiundiksha-shandi',
    storageBucket: 'koperasiundiksha-shandi.firebasestorage.app',
    iosBundleId: 'com.example.tesModulLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKh14iH24uTYEDBvKBf47Ap-gouJzm1M8',
    appId: '1:673637170831:ios:93c79c6f6368db8e80fafa',
    messagingSenderId: '673637170831',
    projectId: 'koperasiundiksha-shandi',
    storageBucket: 'koperasiundiksha-shandi.firebasestorage.app',
    iosBundleId: 'com.example.tesModulLayout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDWdchsUpDJFtg96PH6shv4W75z2ZmIUA',
    appId: '1:673637170831:web:3f0473b7319be5db80fafa',
    messagingSenderId: '673637170831',
    projectId: 'koperasiundiksha-shandi',
    authDomain: 'koperasiundiksha-shandi.firebaseapp.com',
    storageBucket: 'koperasiundiksha-shandi.firebasestorage.app',
    measurementId: 'G-V541WPVYY0',
  );
}
